In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from IPython.display import display

# Sample text data
documents = [
    "Stock prices are rising in the market",
    "The market is volatile due to global events",
    "Investors are looking for safe assets",
    "Technology stocks are gaining momentum"
]

# Initialize TF-IDF Vectorizer
vectorizer = TfidfVectorizer()

# Fit and transform documents
tfidf_matrix = vectorizer.fit_transform(documents)

# Convert to DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())


# Display the result
display(tfidf_df)

,are,assets,due,events,for,gaining,global,in,investors,is,...,momentum,prices,rising,safe,stock,stocks,technology,the,to,volatile
0,0.268515,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.420681,0.000000,0.000000,...,0.00000,0.420681,0.420681,0.000000,0.420681,0.00000,0.00000,0.331670,0.000000,0.000000
1,0.000000,0.000000,0.371565,0.371565,0.000000,0.00000,0.371565,0.000000,0.000000,0.371565,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.292946,0.371565,0.371565
2,0.274487,0.430037,0.000000,0.000000,0.430037,0.00000,0.000000,0.000000,0.430037,0.000000,...,0.00000,0.000000,0.000000,0.430037,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000
3,0.304035,0.000000,0.000000,0.000000,0.000000,0.47633,0.000000,0.000000,0.000000,0.000000,...,0.47633,0.000000,0.000000,0.000000,0.000000,0.47633,0.47633,0.000000,0.000000,0.000000